name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install cargo valgrind
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --target x86_64-unknown-linux-gnu
    - name: Test
      env:
        CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: valgrind --error-exitcode=1 --leak-check=full
        DEBUGINFOD_URLS: ""
      run: cargo test --target x86_64-unknown-linux-gnu
